import React from "react";
import ContentContext from "./contentContext"; 

const ContentState = (props) => {

    const contents = [
        {
            'sentence':'by short nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while never in out fast text water that one  which once new sound take where little work know place year live me back give most very after thing just man think does great help much before boy  follow want show also aorund form three small set put land home about kind hand again change away spell house page letter found study still learn world high try move try rice ice give go cap bag'
        },
        {
            'sentence':'panel google the india chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell  to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while never in out fast text when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while never in out fast text water that one  which once new sound take where little work know place year live me back give most very after thing just man think does great help much before boy'
        },
        {
            'sentence':'great help much before boy  follow want show also around form three small set put land home about kind hand again change away spell house page letter found study still learn world high try move try here  area command station india thane station  this my name is aman line want never think this while never in out fast text water that one  which once new sound take where little work know place year live me back give most very after thing just man think does help much before boy to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel google the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while never in out fast text'
        },
        {
            'sentence':'google the india chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell name is aman line want never think this while never in out fast text when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while never in out fast text water that one  which once new sound take where little work know place year live me back give most very after thing just man this my name is aman nation from to your name you can tell when or where some thing happen is a group of words that begins with goes at the end of the  add short aman to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel the chrome start tor git repo icon react here  area command station india thane station  this my name is aman line want never think this while to your can tell when or where some thing logo were hero name is a total master recycle screen hard disk admin to this that there company a control panel  the chrome start tor git repo icon react here  area command station india thane station  this my name is aman nation from'
        },
        {
            'sentence':'not start here now once what is a hard this there where that cycle work because note site and you next to add given allow let plane many number about help meet try near joint follow part so has meet contains drop prove show delete show want wish drop stop elect choose count ensure clear spend end expend failed  didnt women for give up lose often needs below same find name once sign first instea to about meet interface applies aman may seems change need monitor notify let know tell many operate option best most choice, way otion way take part let about of on part portion permit have own possess previous before before rank skill give offer say provide buy to by following per under about on move relative move to and once move relocate rest pay payment remuneration remain give require must need is keep live said some such the this that keep selection like ask for request choice latest give send submit subject later , next after later then enough subject end stop there are there are there in so there the under us  e of time promptsend type transmit under until use confirm validate viable practicl workable all call for permit because since about saw and or your officesaw and or '
        }
    ]

    return ( < > 

        <ContentContext.Provider value={ contents }>
            { props.children } 
        </ContentContext.Provider>
    </>
    )
}

export default ContentState;